
@local = http://localhost:5566
//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v2/gestao/export
Content-Type: application/x-www-form-urlencoded

&uid='99999'
&db_schema='dia'












