
//@local = http://localhost:5566
@local = https://bigboxapi.profitmais.com.br
//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v2/gestao/file-download
Content-Type: application/x-www-form-urlencoded

&db_schema='dia'












