
//@local = http://localhost:5566

@local = https://bigboxapi.profitmais.com.br


@schema ='semar'

//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v2/gestao/pesquisas
Content-Type: application/x-www-form-urlencoded

&cluster='UBATUBA'
&codigo_pai='1817'
&tipo_concorrente='PRIMARIO'
&db_schema={{schema}}












