
//@local = http://localhost:5566

@local = https://bigboxapi.profitmais.com.br


@schema ='dia'

//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************
POST {{local}}/api/v2/gestao/pesquisas
Content-Type: application/x-www-form-urlencoded

&cluster='SP - CAPITAL/GDE SP - ALTO'
&codigo_pai='37145'
&tipo_concorrente='PRIMARIO'
&db_schema={{schema}}


###
//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************
POST {{local}}/api/v2/gestao/pesquisas
Content-Type: application/x-www-form-urlencoded

&cluster='BIG BOX CENTRO'
&codigo_pai='6550-1'
&tipo_concorrente='ESTUDO'
&db_schema='pricing_bigbox'










