
//@local = http://localhost:5566
@local = https://bigboxapi.profitmais.com.br
@schema = 'dia'
//***********************************************
//  classificador/diferenca-total
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v2/gestao/classificador/slider-filtro
Content-Type: application/x-www-form-urlencoded

&grupo=null
&fornecedor=null
&produto=null
&bandeira='DIA'
&sensibilidade=null
&papel_categoria=null
&sub_grupo=null
&cluster=null
&departamento=null
&secao=null
&slider='2'
&maioriguala='0'
&abaixo_de=null
&acima_de='50'
&registros='200'
&pagina='1'
&db_schema='dia'


###
POST {{local}}/api/v2/gestao/classificador/slider-filtro
Content-Type: application/x-www-form-urlencoded

&grupo=null
&fornecedor=null
&produto=null
&bandeira=null
&sensibilidade=null
&papel_categoria=null
&sub_grupo=null
&cluster=null
&departamento=null
&secao=null
&slider='2'
&maioriguala='20'
&registros='50'
&pagina='3'
&db_schema={{schema}}

###
POST {{local}}/api/v2/gestao/classificador/slider-filtro
Content-Type: application/x-www-form-urlencoded

&grupo=null
&fornecedor=null
&produto=null
&bandeira=null
&nome_bandeira=null
&sensibilidade=null
&papel_categoria=null
&sub_grupo=null
&subgrupo=null
&cluster=null
&departamento=null
&secao=null
&registros='150'
&pagina='1'
&db_schema='dia'
&tipo='pais'
&slider='1'
&maioriguala='0'
&abaixo_de='-2243'
&acima_de='2417'







