
//@local = http://localhost:5566

@local = https://bigboxapi.profitmais.com.br

//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v2/gestao/totalizadores
Content-Type: application/x-www-form-urlencoded

&grupo=null
&fornecedor=null
&produto=null
&bandeira=null
&sensibilidade=null
&papel_categoria=null
&sub_grupo=null
&cluster=null
&departamento=null
&secao=null
&db_schema='dia'


//Mrg Objetiva ------> margem_objetiva_ponderada2
//Mrg Reg Atual -----> margem_atual_ponderada2
//Mrg Reg Sugestão --> margem_nova_ponderada2
//Mrg Reg Final -----> margem_real









