
//@local = http://localhost:5566

@local = https://bigboxapi.profitmais.com.br
@schema ='semar'
###
//***********************************************
//  atualiza valores
//***********************************************

POST {{local}}/api/v2/gestao/update
Content-Type: application/x-www-form-urlencoded

&cluster='MG - BH BAIXO'
&codigo_pai='167292'
&analizado='2'
&exportado='0'
&preco_decisao='4.79'
&uid='99999'
&db_schema='dia'


###
//***********************************************
//  atualiza valores no modo teste
//***********************************************

POST {{local}}/api/v2/gestao/update-teste
Content-Type: application/x-www-form-urlencoded

&cluster='SP - LITORAL'
&codigo_pai='84776'
&analizado='1'
&exportado='0'
&preco_decisao='16.30'
&uid='99999'
&db_schema='dia'

###
# SEMAR
#.........................

POST {{local}}/api/v2/gestao/update
Content-Type: application/x-www-form-urlencoded

&cluster='SUZANO'
&codigo_pai='131523'
&analizado='1'
&exportado='0'
&preco_decisao='40.49'
&uid='88888'
&db_schema='semar'








