
@local = http://localhost:5566
//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v1/gestao/export
Content-Type: application/x-www-form-urlencoded

&uid='99999'
&data='14/10/2020'













