
//@local = http://localhost:5566


@local = https://bigboxapi.profitmais.com.br




//***********************************************
//  
//  s
//***********************************************

POST {{local}}/api/v1/gestao/filtro/paisefilhos
Content-Type: application/x-www-form-urlencoded

&grupo=null
&fornecedor=null
&produto=null
&bandeira=nulls
&sensibilidade=null
&papel_categoria=null
&sub_grupo=null
&cluster=null
&departamento=null
&secao=null
&registros='250'
&pagina='1'













