
@local = http://localhost:5566

//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v2/gestao/filtro-dependentes
Content-Type: application/x-www-form-urlencoded

&grupo=null
&fornecedor=null
&produto=null
&bandeira=null
&sensibilidade=null
&papel_categoria=null
&sub_grupo=null
&cluster=null
&departamento=null
&secao=null
&db_schema='dia'












