
@local = http://localhost:5566
//***********************************************
//  filtrodependentes
//  pesquisa itens baseado em uma string
//***********************************************

POST {{local}}/api/v1/gestao/update
Content-Type: application/x-www-form-urlencoded

&cluster='ULTRABOX SUDESTE'
&codigo_pai='1-9'
&analisado='1'
&exportado='0'
&preco_decisao='2.02'
&uid='99999'
&db_schema='dia'












