
//@local = http://localhost:5566

@local = https://apipp.profitmais.com.br
@schema ='pricing_bigbox'

//***********************************************
//  
//***********************************************

GET {{local}}/api/users/



###
GET {{local}}/api/users/config/fernando.antonio@bigbox.com.br

###
GET {{local}}/api/users/config/cyymacena@icloud.com


###
GET {{local}}/api/users/config/pricepoint.bigbox@profitmais.com.br

###
GET {{local}}/api/users/config/pricepoint.ikesaki@profitmais.com.br

###profit demo portugues
GET {{local}}/api/users/config/pricepoint.profit@profitmais.com.br

###MAMBO
GET {{local}}/api/users/config/pricepoint.mambo@profitmais.com.br


###UNIDASUL
GET {{local}}/api/users/config/pricepoint.unidasul@profitmais.com.br






