
@local = http://localhost:5566
//@local = https://apipp.profitmais.com.br

#database de referencia
@db=semar

@filters='{bandeira:null,cluster:null,departamento:null,secao:null,grupo:null,sub_grupo:null,produto:null,sensibilidade:null,papel_categoria:null,escala:null,fornecedor:null}'
@bandeira=null
@cluster=null
@departamento='BAZAR,BEBIDAS'
@secao=null
@grupo=null
@subgrupo=null
@papel_categoria=null
@sensibilidade=null
@fornecedor=null
@schema='semar'

###
GET {{local}}/api/v2/filters/semar
Content-Type: application/x-www-form-urlencoded

# ****************************************************
# filtro dependente
# ****************************************************

###
POST {{local}}/api/v2/gestao/filtro-dependentes
Content-Type: application/x-www-form-urlencoded


&bandeira={{bandeira}}
&cluster={{cluster}}
&departamento={{departamento}}
&secao={{secao}}
&grupo={{grupo}}
&sub_grupo={{subgrupo}}
&papel_categoria={{papel_categoria}}
&sensibilidade={{sensibilidade}}
&fornecedor={{fornecedor}}
&db_schema={{schema}}

