
//@local = http://localhost:5566
@local = https://apipp.profitmais.com.br

#database de referencia
@db=semar

@bandeira=null
@cluster='FERRAZ'
@departamento=null
@secao=null
@grupo=null
@subgrupo='AVES'
@papel_categoria=null
@sensibilidade=null
@fornecedor=null
@schema='semar'

###
GET {{local}}/api/v2/filters/{{db}}
Content-Type: application/x-www-form-urlencoded

# ****************************************************
# filtro dependente
# ****************************************************

###
POST {{local}}/api/v2/gestao/filtro-dependentes
Content-Type: application/x-www-form-urlencoded

&grupo={{grupo}}
&fornecedor={{fornecedor}}
&produto=null
&bandeira={{bandeira}}
&sensibilidade={{sensibilidade}}
&papel_categoria={{papel_categoria}}
&sub_grupo={{subgrupo}}
&cluster={{cluster}}
&departamento={{departamento}}
&secao={{secao}}
&registros='250'
&pagina='1'
&db_schema={{schema}}
